version: "3.8"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  ### NGINX ##################################
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - "./:/app/ui/public"
    networks:
      - frontend
      - backend

  ### ui ################################
  ui:
    build:
      context: ./docker/ui
    ports:
      - "3000:3000"
      - "35729:35729"
    stdin_open: true
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=production
      - BROWSER=none
      - CHOKIDAR_USEPOLLING=true
    expose:
      - "3000"
      - "35729"
    networks:
      - frontend
      - backend
    volumes:
      - "./:/app"
    command: "yarn start"
