# pull official base image
FROM node:12.19-alpine

# set working directory
WORKDIR /app

#RUN yarn install --silent

# add app
#COPY . /app

# expose api port
EXPOSE 3000

# start app
CMD ["yarn", "start"]
